### ISSUE TITLE
Function _get_y has a high probability of failing to converge

### ISSUE THREAD

**Issue by guotie** [aerodrome-finance/contracts#11] opened 2024-09-15 05:31 UTC
Function _get_y has a high probability of failing to converge

I have a test on all stable pools, amountIn is 1/100000 of reserve0 or reserve1, this is the log:

```

{"level":"warn","time":1726377931132,"message":"_get_y: !y x0=6374819617674754 xy=14632490190445667764424993533 y=13191173941155845203024"}
{"level":"warn","time":1726377931135,"message":"_get_y: !y x0=49080790369518028 xy=66227422591132056020 y=11050262108420851697"}
{"level":"warn","time":1726377931147,"message":"_get_y: !y x0=13717683910025743 xy=13547759506636889707553 y=99585374215816842848"}
{"level":"warn","time":1726377931159,"message":"_get_y: !y x0=11801395600034842 xy=7398392133135042528177 y=85585722857835552124"}
{"level":"warn","time":1726377931221,"message":"_get_y: !y x0=6934284564042172 xy=15111895825122997695759684 y=1296499729148865996321"}
{"level":"warn","time":1726377931238,"message":"_get_y: !y x0=292938829063 xy=5552605282603329 y=26662853118570998255"}
{"level":"warn","time":1726377931244,"message":"_get_y: !y x0=215781762830794 xy=4782478468507533693 y=28089634973504576686"}
{"level":"warn","time":1726377931257,"message":"_get_y: !y x0=20058214489944001 xy=3965000300712663133914418434 y=5825282405658313090430"}
{"level":"warn","time":1726377931261,"message":"_get_y: !y x0=154697088994446365 xy=142444279666816529569402 y=97286801339029044922"}
{"level":"warn","time":1726377931323,"message":"_get_y: !y x0=1674631334455757 xy=78085156740240280463071411278 y=35992865574659055973161"}
{"level":"warn","time":1726377931340,"message":"_get_y: !y x0=6153977503906669 xy=575145641761159090940 y=45380990806161940965"}
{"level":"warn","time":1726377931525,"message":"_get_y: !y x0=81042035608968468 xy=16503836869362841914564572 y=588335233474487150422"}
{"level":"warn","time":1726377931535,"message":"_get_y: !y x0=30974844135520163 xy=17170490928643444349277211679 y=8214690288497615789101"}
{"level":"warn","time":1726377931538,"message":"_get_y: !y x0=2839710576812779 xy=916507484934352659094841 y=685941868874136277365"}
{"level":"warn","time":1726377931554,"message":"_get_y: !y x0=150432527611803 xy=18067756736444456199358603 y=4933867633142315282597"}
{"level":"warn","time":1726377931624,"message":"_get_y: !y x0=2714743840901174 xy=770633407203255267936289024 y=6572132719738160052123"}
{"level":"warn","time":1726377931646,"message":"_get_y: !y x0=787114592487270 xy=342960089029776930345550033679 y=75811520387464076891255"}
```

**Comment by TechGeorgii** [comment] 2024-10-21 05:42
Not sure if it is related, have a look at tx https://basescan.org/tx/0x54b3aecc2e20469532b723838beb85574731d79793d403001028d8a0135b9dd4

It is failing due to the overflow trying to compute _get_y (when computing _k).

Can it be a bug in the contract?

**Comment by stas** [comment] 2024-10-31 12:33
There's a bunch of fixes around `_get_y` and `_k` computation that will be published with the new release.

I'll be closing the issue because the information here is not providing steps to reproduce an issue. Happy to re-open if you can draft a proper PoC.

Thank you.

**Closed as completed by stas** 2024-10-31 12:33 UTC
